title: "Saints Church | Reformed Baptist Church in Knoxville, TN"
email: contact@saintschurchknox.com
description: "Saints Church, Knoxville TN—Bible-centered, Reformed Baptist. Expository preaching, 1689 Confession, Acts 2:42–47 fellowship. Sundays 9:30 AM at 11213 Outlet Dr."
baseurl: ""
url: "https://saintschurchknox.com"
keywords: "Reformed Baptist church Knoxville, LBC church Tennessee, expository preaching, London Baptist Confession, Bible teaching Knoxville, Christian church near me"
church:
  name: "Saints Church"
  address:
    street: "11213 Outlet Dr"
    city: "Knoxville"
    state: "TN"
    zip: "37932"
    country: "United States"
  phone: "(865) 555-0123"
  service_times:
    sunday: "9:30 AM"
    prayer_meeting: "Monthly"
  denomination: "Reformed Baptist"
  confession: "London Baptist Confession (1689)"

# Build settings
strict_front_matter: true
show_drafts: false
future: false

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# URL structure
permalink: pretty

# Performance (GitHub Pages compatible)
sass:
  style: compressed

# Podcast/Sermon configuration
podcast:
  title: "Saints Church Sermon Feed"
  description: "Expository preaching from Saints Church in Knoxville, TN. Reformed Baptist sermons verse-by-verse through Scripture."
  language: "en-us"
  author: "Pastor Nate Ellis"
  email: "contact@saintschurchknox.com"
  copyright: "© Saints Church"
  categories: ["Religion & Spirituality", "Christianity"]
  explicit: "no"
  rss_url: "https://anchor.fm/s/f5d78a70/podcast/rss"
  platforms:
    apple: "https://podcasts.apple.com/us/podcast/saints-church-sermon-feed/id1744952518"
    spotify: "https://open.spotify.com/show/56Dd1OdPxjZ6FfkjJhHQG9"
    overcast: "https://overcast.fm/itunes1744952518/saints-church-sermon-feed"

# Post defaults for sermons
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "sermon"
      category: "sermon"
      permalink: "/sermons/:title/"
