title: "Saints Church | Reformed Baptist Church in Knoxville, TN"
email: contact@saintschurchknox.com
description: "Saints Church, Knoxville TN—Bible-centered, Reformed Baptist. Expository preaching, 1689 Confession, Acts 2:42–47 fellowship. Sundays 9:30 AM at 11213 Outlet Dr."
baseurl: ""
url: "https://saintschurchknox.com"
keywords: "Reformed Baptist church Knoxville, LBC church Tennessee, expository preaching, London Baptist Confession, Bible teaching Knoxville, Christian church near me"
church:
  name: "Saints Church"
  address:
    street: "11213 Outlet Dr"
    city: "Knoxville"
    state: "TN"
    zip: "37932"
    country: "United States"
  phone: "(865) 555-0123"
  service_times:
    sunday: "9:30 AM"
    prayer_meeting: "Monthly"
  denomination: "Reformed Baptist"
  confession: "London Baptist Confession (1689)"

plugins:
  - jekyll-feed
  - jekyll-sitemap
