#!/usr/bin/env node
'use strict';
/**
 * Generate preacher avatar variants + inline LQIP placeholders.
 *
 * For every preacher in _data/preachers.yml, emits from assets/images/<image>.jpg:
 *   - <image>-64w.webp   (1x for the largest on-page use)
 *   - <image>-128w.webp  (2x)
 * and writes a 16px base64 WebP placeholder per preacher into _data/avatars.yml,
 * which _includes/pastor-image.html inlines as a background so the avatar paints
 * on first paint with no request.
 *
 * AVIF is deliberately absent: its fixed container overhead makes it 5-50x larger
 * than WebP at these dimensions (measured 544-6031 bytes vs 90-138 at 16px).
 *
 * Requires ImageMagick (`magick`). Not part of the CI freshness gate -- the output
 * is committed like the other pre-sized image variants in assets/images/.
 *
 * Usage: yarn generate-avatars
 */

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { execFileSync } = require('node:child_process');
const yaml = require('js-yaml');

const ROOT = path.join(__dirname, '..');
const IMAGES_DIR = path.join(ROOT, 'assets', 'images');
const PREACHERS = path.join(ROOT, '_data', 'preachers.yml');
const OUT = path.join(ROOT, '_data', 'avatars.yml');

const WIDTHS = [64, 128];
const LQIP_WIDTH = 16;

function magick(src, dest, width, quality) {
  // -strip matters: two source photos carry ICC profiles that dwarf a 16px payload
  execFileSync('magick', [
    src,
    '-strip',
    '-resize',
    `${width}x${width}`,
    '-quality',
    String(quality),
    dest,
  ]);
}

function main() {
  try {
    execFileSync('magick', ['-version'], { stdio: 'ignore' });
  } catch {
    console.error('ImageMagick not found. Install it with: brew install imagemagick');
    process.exit(1);
  }

  const preachers = yaml.load(fs.readFileSync(PREACHERS, 'utf8'));
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'avatars-'));
  const lqip = {};

  for (const preacher of preachers) {
    const src = path.join(IMAGES_DIR, `${preacher.image}.jpg`);
    if (!fs.existsSync(src)) {
      console.error(`  missing source: ${src}`);
      process.exit(1);
    }

    for (const width of WIDTHS) {
      const dest = path.join(IMAGES_DIR, `${preacher.image}-${width}w.webp`);
      magick(src, dest, width, 82);
      console.log(`  ${preacher.image}-${width}w.webp -> ${fs.statSync(dest).size} bytes`);
    }

    const placeholder = path.join(tmp, `${preacher.image}.webp`);
    magick(src, placeholder, LQIP_WIDTH, 60);
    const encoded = fs.readFileSync(placeholder).toString('base64');
    lqip[preacher.image] = `data:image/webp;base64,${encoded}`;
    console.log(`  ${preacher.image} placeholder -> ${encoded.length} base64 chars`);
  }

  fs.rmSync(tmp, { recursive: true, force: true });

  const header = '# Generated by scripts/generate-avatars.js - do not edit by hand\n';
  fs.writeFileSync(OUT, header + yaml.dump({ lqip }, { lineWidth: -1 }));
  console.log(`\nWrote ${path.relative(ROOT, OUT)} for ${preachers.length} preachers.`);
}

main();
